// <auto-generated />
using System;
using FileService.Infrastructure.Postgres;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FileService.Infrastructure.Postgres.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260915184229_AddedUploadIdColumn")]
    partial class AddedUploadIdColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("files")
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FileService.Domain.Assets.MediaAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("asset_type");

                    b.Property<DateTimeOffset>("CreatedWhen")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_when");

                    b.Property<bool>("IsTemporary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_temporary");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedWhen")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_when");

                    b.Property<string>("UploadId")
                        .HasColumnType("text")
                        .HasColumnName("upload_id");

                    b.Property<string>("asset_kind")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.HasKey("Id");

                    b.HasIndex("AssetType")
                        .HasDatabaseName("ix_media_assets_asset_type");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_media_assets_status");

                    b.ToTable("media_assets", "files");

                    b.HasDiscriminator<string>("asset_kind").HasValue("MediaAsset");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("FileService.Domain.Assets.AudioAsset", b =>
                {
                    b.HasBaseType("FileService.Domain.Assets.MediaAsset");

                    b.HasDiscriminator().HasValue("audio");
                });

            modelBuilder.Entity("FileService.Domain.Assets.DocumentAsset", b =>
                {
                    b.HasBaseType("FileService.Domain.Assets.MediaAsset");

                    b.HasDiscriminator().HasValue("document");
                });

            modelBuilder.Entity("FileService.Domain.Assets.PreviewAsset", b =>
                {
                    b.HasBaseType("FileService.Domain.Assets.MediaAsset");

                    b.HasDiscriminator().HasValue("preview");
                });

            modelBuilder.Entity("FileService.Domain.Assets.VideoAsset", b =>
                {
                    b.HasBaseType("FileService.Domain.Assets.MediaAsset");

                    b.HasDiscriminator().HasValue("video");
                });

            modelBuilder.Entity("FileService.Domain.Assets.MediaAsset", b =>
                {
                    b.OwnsOne("FileService.Domain.MediaData", "MediaData", b1 =>
                        {
                            b1.Property<Guid>("MediaAssetId")
                                .HasColumnType("uuid");

                            b1.Property<long>("ExpectedChunksCount")
                                .HasColumnType("bigint")
                                .HasColumnName("expected_chunks_count");

                            b1.HasKey("MediaAssetId");

                            b1.ToTable("media_assets", "files");

                            b1.WithOwner()
                                .HasForeignKey("MediaAssetId");

                            b1.OwnsOne("FileService.Domain.ValueObjects.ContentType", "ContentType", b2 =>
                                {
                                    b2.Property<Guid>("MediaDataMediaAssetId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Category")
                                        .IsRequired()
                                        .HasMaxLength(255)
                                        .HasColumnType("character varying(255)")
                                        .HasColumnName("content_category");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(255)
                                        .HasColumnType("character varying(255)")
                                        .HasColumnName("content_type");

                                    b2.HasKey("MediaDataMediaAssetId");

                                    b2.ToTable("media_assets", "files");

                                    b2.WithOwner()
                                        .HasForeignKey("MediaDataMediaAssetId");
                                });

                            b1.OwnsOne("FileService.Domain.ValueObjects.FileName", "FileName", b2 =>
                                {
                                    b2.Property<Guid>("MediaDataMediaAssetId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Extension")
                                        .IsRequired()
                                        .HasMaxLength(255)
                                        .HasColumnType("character varying(255)")
                                        .HasColumnName("file_extension");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasMaxLength(255)
                                        .HasColumnType("character varying(255)")
                                        .HasColumnName("file_name");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(510)
                                        .HasColumnType("character varying(510)")
                                        .HasColumnName("file_name_full");

                                    b2.HasKey("MediaDataMediaAssetId");

                                    b2.ToTable("media_assets", "files");

                                    b2.WithOwner()
                                        .HasForeignKey("MediaDataMediaAssetId");
                                });

                            b1.OwnsOne("FileService.Domain.ValueObjects.FileSize", "FileSize", b2 =>
                                {
                                    b2.Property<Guid>("MediaDataMediaAssetId")
                                        .HasColumnType("uuid");

                                    b2.Property<long>("Bytes")
                                        .HasColumnType("bigint")
                                        .HasColumnName("file_size_bytes");

                                    b2.HasKey("MediaDataMediaAssetId");

                                    b2.ToTable("media_assets", "files");

                                    b2.WithOwner()
                                        .HasForeignKey("MediaDataMediaAssetId");
                                });

                            b1.Navigation("ContentType")
                                .IsRequired();

                            b1.Navigation("FileName")
                                .IsRequired();

                            b1.Navigation("FileSize")
                                .IsRequired();
                        });

                    b.OwnsOne("FileService.Domain.MediaOwner", "MediaOwner", b1 =>
                        {
                            b1.Property<Guid>("MediaAssetId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Context")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("owner_context");

                            b1.Property<Guid>("EntityId")
                                .HasColumnType("uuid")
                                .HasColumnName("owner_entity_id");

                            b1.HasKey("MediaAssetId");

                            b1.HasIndex("Context", "EntityId")
                                .HasDatabaseName("ix_media_assets_owner");

                            b1.ToTable("media_assets", "files");

                            b1.WithOwner()
                                .HasForeignKey("MediaAssetId");
                        });

                    b.OwnsOne("FileService.Domain.ValueObjects.StorageKey", "StorageKey", b1 =>
                        {
                            b1.Property<Guid>("MediaAssetId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Bucket")
                                .IsRequired()
                                .HasMaxLength(1024)
                                .HasColumnType("character varying(1024)")
                                .HasColumnName("storage_bucket");

                            b1.Property<string>("FullPath")
                                .IsRequired()
                                .HasMaxLength(1024)
                                .HasColumnType("character varying(1024)")
                                .HasColumnName("storage_full_path");

                            b1.Property<string>("Key")
                                .IsRequired()
                                .HasMaxLength(1024)
                                .HasColumnType("character varying(1024)")
                                .HasColumnName("storage_key");

                            b1.Property<string>("Prefix")
                                .IsRequired()
                                .HasMaxLength(1024)
                                .HasColumnType("character varying(1024)")
                                .HasColumnName("storage_prefix");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(1024)
                                .HasColumnType("character varying(1024)")
                                .HasColumnName("storage_value");

                            b1.HasKey("MediaAssetId");

                            b1.HasIndex("Bucket", "Prefix", "Key")
                                .IsUnique()
                                .HasDatabaseName("ux_media_assets_storage_key");

                            b1.ToTable("media_assets", "files");

                            b1.WithOwner()
                                .HasForeignKey("MediaAssetId");
                        });

                    b.OwnsOne("FileService.Domain.ValueObjects.StorageMetadata", "StorageMetadata", b1 =>
                        {
                            b1.Property<Guid>("MediaAssetId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ContentType")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("storage_metadata_actual_content_type");

                            b1.Property<string>("ETag")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("storage_metadata_e_tag");

                            b1.Property<long>("SizeBytes")
                                .HasColumnType("bigint")
                                .HasColumnName("storage_metadata_actual_size_bytes");

                            b1.HasKey("MediaAssetId");

                            b1.ToTable("media_assets", "files");

                            b1.WithOwner()
                                .HasForeignKey("MediaAssetId");
                        });

                    b.Navigation("MediaData")
                        .IsRequired();

                    b.Navigation("MediaOwner")
                        .IsRequired();

                    b.Navigation("StorageKey")
                        .IsRequired();

                    b.Navigation("StorageMetadata")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
