<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\FileService.Contracts\FileService.Contracts.csproj" />
    <ProjectReference Include="..\FileService.Domain\FileService.Domain.csproj" />
    <ProjectReference Include="..\FileService.Shared.Messaging\FileService.Shared.Messaging.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="mazeland.core" />
    <PackageReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.Extensions.Caching.Hybrid" />
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" />
    <PackageReference Include="WolverineFx.EntityFrameworkCore" />
    <PackageReference Include="WolverineFx.Postgresql" />
    <PackageReference Include="WolverineFx.RabbitMQ" />
    <PackageReference Include="WolverineFx.RuntimeCompilation" />
  </ItemGroup>
</Project>
